# Generated by Django 5.2.5 on 2025-08-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='narrador_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videogerado',
            name='volume_musica',
            field=models.IntegerField(default=70),
        ),
    ]
