# Generated by Django 5.2.5 on 2025-08-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_videogerado_narrador_texto_videogerado_volume_musica'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='narrador_voz',
            field=models.CharField(default='pt-BR-Neural2-A', max_length=50),
        ),
    ]
