# Generated by Django 5.2.5 on 2025-08-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pagamento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
