# Generated by Django 5.2.5 on 2025-08-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='plano_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
