# Generated by Django 5.2.5 on 2025-08-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_videogerado_narrador_voz'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='narrador_tom',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='videogerado',
            name='narrador_velocidade',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='videogerado',
            name='narrador_voz',
            field=models.CharField(default='pt-BR-Wavenet-B', max_length=50),
        ),
    ]
