# Generated by Django 5.2.5 on 2025-08-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_plano_ativo_usuario_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='recursos',
            field=models.TextField(default='Recursos do plano'),
        ),
        migrations.AddField(
            model_name='plano',
            name='stripe_price_id',
            field=models.CharField(default='price_default', max_length=100),
        ),
        migrations.AddField(
            model_name='plano',
            name='videos_por_mes',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='plano',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plano',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
