# Generated by Django 5.2.5 on 2025-08-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_videogerado_narrador_tom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='plano_de_fundo',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
