# Generated by Django 5.2.5 on 2025-08-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_videogerado_plano_de_fundo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='texto_fonte',
            field=models.CharField(default='arial', max_length=50),
        ),
        migrations.AddField(
            model_name='videogerado',
            name='texto_tamanho',
            field=models.IntegerField(default=50),
        ),
    ]
