# Generated by Django 5.2.5 on 2025-08-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_plano_ativo_plano_recursos_plano_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plano',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='plano',
            name='stripe_price_id',
            field=models.CharField(max_length=100),
        ),
    ]
