# Generated by Django 5.2.5 on 2025-08-23 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_plano_descricao_alter_plano_preco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='recursos',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='videos_por_mes',
        ),
    ]
