# Generated by Django 5.2.5 on 2025-08-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_videogerado_texto_fonte_videogerado_texto_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='texto_negrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videogerado',
            name='texto_sublinhado',
            field=models.BooleanField(default=False),
        ),
    ]
