# Generated by Django 5.2.5 on 2025-08-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_videogerado_texto_negrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='legenda_sincronizada',
            field=models.BooleanField(default=False),
        ),
    ]
