# Generated by Django 5.2.5 on 2025-08-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_plano_ativo_remove_plano_recursos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='pendente', max_length=10),
        ),
    ]
