# Generated by Django 5.2.5 on 2025-08-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_videogerado_legenda_sincronizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogerado',
            name='duracao_minutos',
        ),
        migrations.AddField(
            model_name='videogerado',
            name='duracao_segundos',
            field=models.IntegerField(default=30),
        ),
    ]
