# Generated by Django 5.2.5 on 2025-08-24 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_assinatura_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_videos_mes', models.PositiveIntegerField(default=100, help_text='Quantos vídeos este usuário pode gerar a cada 30 dias.')),
                ('max_videos_em_lote', models.PositiveIntegerField(default=3, help_text='Quantos vídeos podem ser gerados de uma só vez no formulário.')),
                ('pode_usar_legendas_karaoke', models.BooleanField(default=True, help_text='Marque se o usuário pode usar a função de legenda dinâmica.')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
