# Generated by Django 5.2.5 on 2025-08-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_videogerado_duracao_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='cor_da_fonte',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
