# Generated by Django 5.2.5 on 2025-08-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_videogerado_cor_da_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='posicao_texto',
            field=models.CharField(default='centro', max_length=10),
        ),
    ]
