# Generated by Django 5.2.5 on 2025-08-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_telafinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogerado',
            name='texto_tela_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TelaFinal',
        ),
    ]
